name: Deploy docs

on:
   push:
      branches:
         - main

jobs:
   build_and_deploy:
      if: "${{ !startsWith(github.event.head_commit.message, 'Merge pull request') && !startsWith(github.event.head_commit.message, 'chore(deps)') && !contains(github.event.head_commit.message, 'chore: release') }}"

      runs-on: ubuntu-latest

      steps:
         - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

         - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
           with:
              node-version: lts/*

         - uses: pnpm/action-setup@ea17c68df8912ef543352723c149a84f56e3d413 # v6.1.0

         - name: Install dependencies
           run: pnpm ci

         - name: Build
           run: pnpm build

         - name: Deploy project to Firebase
           uses: FirebaseExtended/action-hosting-deploy@500ac625ca2dd40cbd15f7659af953801858032a # v0.11.0
           with:
              repoToken: "${{ secrets.GITHUB_TOKEN }}"
              firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASTRO_LQIP }}"
              channelId: live
              entryPoint: ./docs
              projectId: astro-lqip
           env:
              FIREBASE_CLI_EXPERIMENTS: webframeworks
